<?php
/**
 * @file
 * A module for working with diva.js
 */


/**
 * Implements hook_help.
 *
 * Displays help and module information
 *
 * @param path
 *  Which path of the site we're using to display help
 * @param arg
 *  Array that holds the current path as returned from arg() function.
 */
function diva_help($path, $arg) {
    switch ($path) {
        case 'admin/help#diva':
            return '<p>'. t("Working with diva.js") . "</p>";
            break;
        default:
            # code...
            break;
    }
}

/**
 * Implements hook_perm
 */

function diva_perm() {
    return array("administer diva module");
}

/**
 * Implements hook_menu.
 */
function diva_menu() {
    $items = array();

    $items['admin/config/diva'] = array(
        'title' => "Diva",
        'description' => "Configuration for the Diva module",
        'position' => "right",
        'weight' => -100,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array("administer diva module"),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );

    $items['admin/config/diva/config'] = array(
        'title' => "Diva Config",
        'description' => 'Configuration for the Diva module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('diva_admin_form'),
        'access arguments' => array('administer diva.js'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function diva_admin_form($form, &$form_state) {
    $form['diva_path_to_vips'] = array(
        '#type' => 'textfield',
        '#title' => t('Path to the VIPS executable'),
        '#default_value' => variable_get('diva_path_to_vips', '/usr/local/bin'),
        '#size' => 12,
        '#maxlength' => 64,
        '#description' => t("The path where the vips software is installed."),
    );

    $form['diva_image_server'] = array(
        '#type' => 'textfield',
        '#title' => t("IIP Image Server"),
        '#default_value' => variable_get('diva_image_server', 'http://example.com:9000/iipsrv.fcgi'),
        '#size' => 64,
        '#maxlength' => 128,
        '#description' => t("Location of the IIP Image Server"),
    );

    $form['diva_default_tile_size'] = array(
        '#type' => 'textfield',
        '#title' => t("Default Tile Size"),
        '#default_value' => variable_get("diva_default_tile_size", "256x256"),
        '#size' => 12,
        '#maxlength' => 12,
        '#description' => t("Default Diva File Size (wxh)")
    );

    return system_settings_form($form);
}

